spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/twitter_clone
    username: root
    password: 67f5ef99116@C
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: 'org.hibernate.dialect.MySQLDialect'
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

